services:
  # Development service
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production service
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    profiles:
      - prod

  # Build service (for building without running)
  react-build:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./dist:/app/dist
    profiles:
      - build
